# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/kmime' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
